api/src/main/java/org/example/educheck/domain/attendance/service/AttendanceService.java, api/src/main/java/org/example/educheck/domain/course/entity/Course.java, api/src/main/java/org/example/educheck/domain/course/entity/CourseStatus.java, api/src/main/java/org/example/educheck/domain/member/dto/response/RegisteredMemberResponseDto.java, api/src/main/java/org/example/educheck/domain/member/entity/Member.java, api/src/main/java/org/example/educheck/domain/member/service/AuthService.java, api/src/main/java/org/example/educheck/domain/member/staff/dto/request/UpdateStudentRegistrationStatusRequestDto.java, api/src/main/java/org/example/educheck/domain/member/staff/dto/response/UpdateStudentRegistrationStatusResponseDto.java, api/src/main/java/org/example/educheck/domain/member/staff/service/StaffService.java, api/src/main/java/org/example/educheck/domain/member/student/dto/response/StudentInfoResponseDto.java, api/src/main/java/org/example/educheck/domain/member/student/entity/Student.java, api/src/main/java/org/example/educheck/domain/member/student/entity/StudentStatus.java, api/src/main/java/org/example/educheck/domain/registration/entity/Registration.java, api/src/main/java/org/example/educheck/domain/registration/entity/RegistrationStatus.java, api/src/main/java/org/example/educheck/domain/registration/repository/RegistrationRepository.java
- ECR-6
- Registration 테이블 dropDate 컬럼 추가, completionDate 컬럼 추가, status 컬럼 및 enum 클래스 삭제
- Student 테이블 status 컬럼 및 enum 클래스 삭제
- Member 테이블 deleteRequestDate 컬럼 추가
- Course 테이블 status 추가
student.courseParticipationStatus 차후 고려
API명세 수정 필요
=> [ECR-6] feat: 엔티티 변경

api/src/main/java/org/example/educheck/domain/attendance/entity/AttendanceStatus.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/dto/response/today/TodayLectureAttendanceSummary.java, api/src/main/java/org/example/educheck/domain/member/entity/Member.java, api/src/test/java/org/example/educheck/domain/attendanceRegister/dto/response/today/TodayLectureAttendanceSummaryTest.java
- ECR-8
- UPCOMING -> NOT_CHECKIN (수업 예정 -> 미출석)
- 수업 시잔 전 시간 : 수업 예정 -> 수업 종료 전 : 미출석 판단 기준 변경
=> [ECR-8] BE/refactor: 관리자 금일 출결 현황 상태값 수정

api/src/main/java/org/example/educheck/domain/member/dto/LoginResponseDto.java, api/src/main/java/org/example/educheck/domain/member/repository/MemberRepository.java, api/src/main/java/org/example/educheck/domain/member/service/AuthService.java
- ECR-12
- loginResponseDto에 isCheckIn 멤버 변수 추가
- memberRepository 메서드 쿼리문 추가
=> [ECR-12] feat: 로그인, 리프레시 시 출석 여부 반환하도록 변경

api/src/main/java/org/example/educheck/domain/attendance/service/AttendanceService.java, api/src/main/java/org/example/educheck/domain/member/repository/MemberRepository.java, client/src/App.jsx, client/src/api/attendanceApi.js, client/src/components/sideBar/SideBar.jsx, client/src/pages/login/Login.jsx
=> [ECR-11] feat: 퇴실 기능 구현

api/src/main/java/org/example/educheck/domain/campus/Campus.java, api/src/main/java/org/example/educheck/domain/meetingroom/entity/MeetingRoom.java, api/src/main/java/org/example/educheck/domain/meetingroomreservation/controller/MeetingRoomReservationController.java, api/src/main/java/org/example/educheck/domain/meetingroomreservation/dto/response/ReservationDto.java, api/src/main/java/org/example/educheck/domain/meetingroomreservation/entity/MeetingRoomReservation.java, api/src/main/java/org/example/educheck/domain/meetingroomreservation/entity/MeetingRoomReservationTime.java, api/src/main/java/org/example/educheck/domain/meetingroomreservation/policy/MeetingRoomReservationPolicy.java, api/src/main/java/org/example/educheck/domain/meetingroomreservation/policy/MemberReservationPolicy.java, api/src/main/java/org/example/educheck/domain/meetingroomreservation/service/MeetingRoomReservationService.java, api/src/main/java/org/example/educheck/domain/member/entity/Member.java, api/src/main/java/org/example/educheck/global/common/time/SystemTimeProvider.java
=> [ECR-13] BE/refactor: 회의실 예약 로직 코드 개선

client/src/components/listItem/leftLineListItem/LeftLineListItem.jsx, client/src/components/listItem/leftLineListItem/LeftLineListItem.module.css, client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.jsx
- ECR-15
- 유고 결석 신청
- 날짜 선택 시 편의성 추가
- 불가능한 날짜 선택 불가능하도록 수정
- 유고 결석 리스트
- 	커서 변경
- 호버 효과 추가
- `...` 위치 조정
=> [ECR-15] fix: 유고 결석 페이지 css 수정

api/src/main/java/org/example/educheck/domain/member/dto/UpdateMyProfileRequestDto.java, api/src/main/java/org/example/educheck/domain/member/service/MyService.java
=> [ECR-16] fix: 회원정보 수정 로직 개선

api/src/main/java/org/example/educheck/domain/member/controller/MyController.java, api/src/main/java/org/example/educheck/domain/member/dto/UpdateMyProfileRequestDto.java, api/src/main/java/org/example/educheck/domain/member/service/MyService.java
- ECR-16
- currentPassword required 추가
- 회원 정보 수정 후 refresh 쿠키 제거
- client에서 access 토큰 삭제 필요
=> [ECR-16] BE/fix: 회원정보 수정 로직 개선

api/src/main/java/org/example/educheck/domain/attendanceRegister/controller/AttendanceRegisterController.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/dto/AttendanceRateProjection.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/dto/response/AttendanceRateProjection.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/dto/response/AttendanceRecordResponseDto.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/dto/response/PageInfo.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/dto/response/PagedAttendanceRecordDto.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/dto/response/StudentAttendanceOverviewDto.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/dto/response/today/TodayLectureAttendanceResponseDto.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/repository/AttendanceRegisterRepository.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/service/AttendanceRegisterService.java, api/src/main/java/org/example/educheck/domain/member/entity/Member.java, api/src/main/java/org/example/educheck/domain/member/staff/entity/Staff.java, api/src/main/java/org/example/educheck/domain/member/student/entity/Student.java, api/src/main/java/org/example/educheck/domain/member/student/repository/StudentRepository.java, api/src/main/java/org/example/educheck/domain/member/student/service/StudentService.java, api/src/main/java/org/example/educheck/domain/studentCourseAttendance/controller/StudentCourseAttendanceController.java, api/src/main/java/org/example/educheck/domain/studentCourseAttendance/dto/AttendanceRateStatisticsDto.java, api/src/main/java/org/example/educheck/domain/studentCourseAttendance/dto/AttendanceRateStatisticsProjection.java, api/src/main/java/org/example/educheck/domain/studentCourseAttendance/dto/AttendanceRecordListResponseDto.java, api/src/main/java/org/example/educheck/domain/studentCourseAttendance/dto/AttendanceRecordResponseDto.java, api/src/main/java/org/example/educheck/domain/studentCourseAttendance/dto/AttendanceStatsProjection.java, api/src/main/java/org/example/educheck/domain/studentCourseAttendance/dto/AttendanceStatsResponseDto.java, api/src/main/java/org/example/educheck/domain/studentCourseAttendance/repository/StudentCourseAttendanceRepository.java, api/src/main/java/org/example/educheck/domain/studentCourseAttendance/service/StudentCourseAttendanceService.java
- ECR-10
- 유효성 검증
- 관리자가 담당 중인 과정 조회 요청하는지 확인
- 수강생이 해당 과정에 등록된 수강생인지 확인
- 불필요한 페이지네이션 정보 제외
- 2차때 불필요한 응답 데이터들이 존재해서 제외하고 응답 및 쿼리 개선
=> [ECR-10] BE/refactor: 관리자 - 수강생 세부 출결 현황 조회 API 리팩터링

api/src/main/java/org/example/educheck/domain/member/entity/Member.java
- ECR-18
- main merge시  conflict 하는 과정에서 누락된 괄호 수정
=> [ECR-18] DE/fix: 괄호 누락 수정

client/src/api/profileApi.js, client/src/components/inputBox/InputBox.module.css, client/src/pages/studentSetting/StudentSetting.jsx
- ECR-17
- api 연동
- 개인 정보 수정 페이지 css 수정
=> [ECR-17] feat: 개인정보 수정 api 연동

client/src/components/tab/Tab.jsx, client/src/components/tab/tabButton/TabButton.jsx
- ECR-21
- 세부 출결 현황이 아닌 페이지에서는 세부 출결 현황이 보이지 않음
=> [ECR-21] feat: 세부 출결 현황 탭 다른 페이지에서 숨기는 기능 구현

api/src/main/java/org/example/educheck/domain/attendanceRegister/controller/AttendanceRegisterController.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/dto/response/AttendanceRecordResponseDto.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/entity/AttendanceRegister.java, client/src/api/attendanceApi.js, client/src/components/listItem/baseListItem/BaseListItem.jsx, client/src/components/tag/Tag.jsx, client/src/pages/staffAttendanceDetail/StaffAttendanceDetail.jsx, client/src/pages/staffAttendanceDetail/StaffAttendanceDetail.module.css
- ECR-19
- 관리자 - 특정 수강생 세부 출결 현황 API 연동
- 출력시 강의명 및 회차 조회 추가
- 페이지네이션 적용
=> [ECR-19] FE/refactor 관리자 세부 출결 현황 api 연동

api/src/main/java/org/example/educheck/domain/attendanceRegister/controller/AttendanceRegisterController.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/dto/response/adminStudentDetail/AttendanceRateProjection.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/dto/response/adminStudentDetail/AttendanceRecordResponseDto.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/dto/response/adminStudentDetail/PagedAttendanceRecordDto.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/dto/response/adminStudentDetail/StudentAttendanceOverviewDto.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/dto/response/myAttendanceStatics/MyAttendanceStaticsProjection.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/dto/response/myAttendanceStatics/MyAttendanceStaticsResponseDto.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/repository/AttendanceRegisterRepository.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/service/AttendanceRegisterService.java, api/src/main/java/org/example/educheck/domain/course/service/CourseService.java, api/src/main/java/org/example/educheck/domain/studentCourseAttendance/controller/StudentCourseAttendanceController.java, api/src/main/java/org/example/educheck/domain/studentCourseAttendance/service/StudentCourseAttendanceService.java
- ECR-22
- 수강생 출석률 및 결석 현황 조회 API 개선
- 변경된 뷰 적용
=> [ECR-22] BE/refactor 출석률 및 결석 현황 조회 api 개선

api/src/main/java/org/example/educheck/domain/member/dto/LoginResponseDto.java, api/src/main/java/org/example/educheck/domain/member/repository/MemberRepository.java
- ECR-28
- 로그인, 리프레시 응답 바디 campusName 추가
- [] 관련 문서 업데이트 (필요한 경우)
=> [ECR-28] fix: dto에 campusName 추가

client/src/pages/login/Login.jsx, client/src/pages/studentSetting/StudentSetting.jsx, client/src/store/slices/authSlice.js
- ECR-29
- 변수명 통일
- 비밀번호 검증 수정
=> [ECR-29] FE/fix: 초기 비밀번호 변경 유도 관련 로직 수정

api/build.gradle, api/compose.yaml, api/src/main/java/org/example/educheck/domain/attendanceRegister/repository/AttendanceRegisterRepository.java, api/src/main/resources/application-test.properties, api/src/test/java/org/example/educheck/domain/attendanceRegister/repository/AttendanceRegisterRepositoryTest.java, api/src/test/resources/test-data.sql, client/src/api/attendanceApi.js, client/src/pages/studentAttendance/StudentAttendance.jsx
- ECR-27
- BE 쿼리 수정
- 조정된 결석 횟수 계산 부분
- FE 코드 정리 및 변수명 수정
=> [ECR-27] BE/refactor 출석률 및 결석 현황 조회 쿼리 수정

client/src/components/privateRoute/PrivateRoute.jsx, client/src/pages/login/Login.jsx, client/src/router/index.jsx
- ECR-32
- 로그아웃 상태에서 router 접근 방지
=> [ECR-32] FE/feat: 로그아웃 상태에서 router 접근 방지

app/app.py
=> [ECR-34] feat: 뷰 변경에 따른 쿼리문 변경

api/src/main/java/org/example/educheck/domain/absenceattendance/controller/AbsenceAttendanceController.java, api/src/main/java/org/example/educheck/domain/absenceattendance/dto/response/PagedMyAbsenceAttendanceResponseDto.java, api/src/main/java/org/example/educheck/domain/absenceattendance/repository/AbsenceAttendanceRepository.java, api/src/main/java/org/example/educheck/domain/absenceattendance/service/AbsenceAttendanceService.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/controller/AttendanceRegisterController.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/dto/response/adminStudentDetail/PagedAttendanceRecordDto.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/repository/AttendanceRegisterRepository.java, api/src/main/java/org/example/educheck/domain/course/entity/Course.java, api/src/main/java/org/example/educheck/global/common/dto/PageInfo.java, client/src/api/absenceAttendancesApi.js, client/src/components/paginationComponent/PaginationComponent.jsx, client/src/pages/studentAttendance/StudentAttendance.jsx, client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.jsx, client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.module.css
- ECR-33
- FE
- 유고 결석 신청 내역 페이지네이션 추가
- BE
- 금일 출결 현황 정렬 순서 변경 : 결석 -> 미출석 -> 이름순
- 유고 결석 신청 내역 정렬 순서 변경 : 미승인 -> 신청 시작일 최신순
=> [ECR-33] BE/refactor 데이터 출력 정렬 기준 변경

client/src/router/index.jsx
=> [ECR-37] FE/fix: router 구조 변경

README.md
- ECR-36
- 프로젝트 소개글, 기간, 링크
- ERD 업데이트 반영
- 팀원 프로필 반영
=> [ECR-36] docs/feat: README 작성

client/src/api/attendanceApi.js, client/src/components/calendar/Calendar.jsx, client/src/components/calendar/calendar.module.css, client/src/css/index.css, client/src/pages/attendanceSheet/AttendanceSheet.module.css, client/src/pages/studentAttendance/StudentAttendance.jsx, client/src/pages/studentAttendance/StudentAttendance.module.css, client/src/router/index.jsx
관리## 🔍 관련 Jira 이슈
- ECR-31
- 달력 출석 정보 추가
- 출석부 css 수정
=> [ECR-31] FE/feat: 수강생 출석 현황 달력 데이터 API 연동

client/src/components/sideBar/SideBar.jsx
=> [ECR-38] FE/fix: 출석 후 퇴실하기로 즉시 바뀌지 않는 문제 해결

app/app.py
- ECR-41
- flask 내부 함수의 매개변수 순서 변경
=> [ECR-41] fix: 매개변수 순서 변경

app/app.py
- ECR-41
- `absent`-> `absence`
=> [ECR-41] fix: flask 내부 dict 수정

api/src/main/java/org/example/educheck/domain/member/controller/DemoAuthController.java, api/src/main/java/org/example/educheck/domain/member/dto/LoginRequestDto.java, api/src/main/java/org/example/educheck/global/security/config/SecurityPathConfig.java, client/src/api/demoAuthApi.js, client/src/pages/attendanceSheet/AttendanceSheet.jsx, client/src/pages/login/Login.jsx, client/src/pages/login/Login.module.css
- ECR-42
- BE
- 데모용 관리자, 수강생 API 엔드포인트 구현 및 환경변수 설정
- Security 인증 필터 제외 Path 설정
- FE
-  데모용 관리자, 수강생 로그인 버튼 생성 및 API 연동
- 로그인 후 accessToken 및 유저 정보 저장 중복 로직 -> handleLoginSuccess 메서드로 분리
- 로컬 BE 환경변수 업데이트 되었습니다. 노션 문서 반영
=> [ECR-42] BE/feat 데모용 로그인 API 구현 및 프론트 연동

client/src/pages/login/Login.jsx, client/src/pages/staffAttendance/StaffAttendance.jsx
랜더링 추가
- ECR-43
- UX 개선 - 강의 없는 날짜인 경우, 금일 출결 현황에 안내 문구
=> [ECR-43] FE/feat:  UX 개선 - 강의 없는 날짜인 경우, 금일 출결 현황에 안내 문구

client/src/pages/roomReservation/RoomReservation.jsx, client/src/pages/staffStudentManage/StaffStudentManage.jsx, client/src/pages/staffStudentManage/StaffStudentManage.module.css
- ECR-44
- 학습자 관리에서 수강생 목록 컴포넌트 클릭 이벤트 추가
- 해당 수강생 세부 출결 현황 이동
- 선택된 CSS 효과 추가
- 추가 사유 :  강의가 없는 날, 학습자 세부 출결 현황을 볼 수 없음
- 회의실 예약 취소 선택시 스크롤 업 이벤트 추가
=> [ECR-44] FE/feat: 학습자 관리 목록 컴포넌트 버튼 이벤트 추가

README.md
- ECR-46
- 서비스, CI/CD 아키텍처 변경된 부분 반영
- API 명세서 링크 첨부
- Figma 와이어프레임 명세서 링크 첨부
=> [ECR-46] docs/chore: README 업데이트

client/src/pages/staffAttendance/StaffAttendance.jsx
- ECR-47
- StaffAttendance에서 summary 데이터가 없는 상황 예외 처리
=> [ECR-47] fix: summary 예외 처리

docker-compose.yml
- ECR-48
- docker compose mysql 추가
=> [ECR-48] feat: mysql 추가

client/templates/default.conf.template, client/templates/https.conf.template, docker-compose.yml
- ECR-49
- nginx config에 domain 추가
- 노션 문서에 환경변수 업데이트 했습니다.
=> [ECR-49] DE/feat: nginx 설정 파일 수정

docker-compose.yml
- ECR-50
- docker-compose.yml client 환경변수 추가
=> [ECR-50] feat: docker-compose.yml client 환경변수 추가

.github/workflows/deploy.yml, client/templates/default.conf.template
=> [ECR-51] DE/fix: nginx 설정 수정

.github/workflows/deploy.yml, client/templates/default.conf.template, client/templates/https.conf.template
=> [ECR-51 DE/fix nginx 설정 수정

.github/workflows/deploy.yml, client/templates/default.conf.template, client/templates/https.conf.template, docker-compose.yml
=> Fix/ecr 51 de nginx 설정 수정

client/templates/https.conf.template
=> [ECR-53] fix: 프록시 경로 수정

client/templates/https.conf.template
Reverts Edu-Check/edu_check_renewal#52
=> Revert "[ECR-53] fix: 프록시 경로 수정"

client/templates/https.conf.template
=> [ECR-54] fix: nginx https config 수정

docker-compose.yml
- ECR-55
- nginx volumes ssl 경로 수정
=> [ECR-55] feat: docker-compose.yml 수정

api/src/main/resources/application.properties, client/src/pages/staffAttendance/StaffAttendance.jsx, client/src/pages/staffAttendanceDetail/StaffAttendanceDetail.jsx, client/src/utils/buttonContentList.js
- ECR-56
-  출결현황 통계 조회 랜더링 수정
- 강의 날짜인지 판별식 수정
- 출석부 상세 조회 Tag 라벨 유고결석 색상 추가 (Tag 공통 컴포넌트에 상태값 추가 - 유고 결석)
=> [ECR-56] FE/fix:  출결현황 통계 조회 랜더링 수정

api/src/main/java/org/example/educheck/domain/attendanceRegister/dto/response/today/TodayLectureAttendanceStatus.java, api/src/main/java/org/example/educheck/domain/attendanceRegister/entity/AttendanceRegisterId.java, client/src/components/paginationComponent/PaginationComponent.jsx, client/src/pages/staffAttendance/StaffAttendance.jsx, client/src/pages/staffAttendanceDetail/StaffAttendanceDetail.jsx
- ECR-57
BE
- 금일 출결 현황 조회 API 응답 student_id 추가
FE
- 금일 출결 현황 조회 API 호출시 파라미터 memberId -> student_id로 변경
- 페이지네이션 컴포넌트 및 상태관리 수정
=> [ECR-57] BE/feat: 금일 출결 현황 응답에 student id 값 추가

client/src/components/paginationComponent/PaginationComponent.jsx, client/src/pages/staffAttendanceDetail/StaffAttendanceDetail.jsx, client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.jsx
- ECR-58
- 유고결석 신청 내역 페이지네이션 수정
=> [ECR-58] fix: 유고결석 신청 내역 페이지네이션 수정

app/app.py, app/requirements.txt
=> BE/[ECR-59] feat: 출석상태 매핑 추가

app/app.py
Reverts Edu-Check/edu_check_renewal#60
=> Revert "BE/[ECR-59] feat: 출석상태 매핑 추가"

api/src/main/java/org/example/educheck/domain/member/staff/controller/StaffController.java, api/src/main/java/org/example/educheck/domain/member/staff/service/StaffService.java, api/src/main/java/org/example/educheck/domain/registration/entity/Registration.java
=> [ECR-61] fix: 수강생 상태 변경 api 수정

api/src/main/java/org/example/educheck/domain/member/student/dto/response/StudentInfoResponseDto.java, api/src/main/java/org/example/educheck/domain/registration/entity/Registration.java, api/src/main/java/org/example/educheck/domain/registration/repository/RegistrationRepository.java
- ECR-62
- 강좌 학생 목록 조회 api 응답 등록상태 필드 추가
=> [ECR-62] fix/ECR-62-BE-과정-수강생-조회-API-응답값-변경

api/src/main/java/org/example/educheck/domain/registration/entity/Registration.java, client/src/api/studentManageApi.js, client/src/components/tag/Tag.jsx, client/src/pages/staffStudentManage/StaffStudentManage.jsx
=> [ECR-63] fix: 등록 상태 api 연동 수정

api/src/main/java/org/example/educheck/domain/attendance/service/AttendanceService.java
- ECR-64
- memberid/studentId 교체
- 출석 예외처리 추가
=> [ECR-64] fix: 퇴실 api 로직 변경

api/src/main/java/org/example/educheck/domain/attendance/service/AttendanceService.java
=> [ECR-68] fix: 출석 유효성 검증 로직 수정

api/.gitignore, api/build.gradle, api/src/main/resources/application-prod.properties, api/src/main/resources/application-test.properties, api/src/main/resources/application.properties, api/src/test/java/org/example/educheck/ProfileCheckTest.java
=> [ECR-71] BE/chore : 프로퍼티 파일 분리

docker-compose.yml
- ECR-72
- docker-compose.yml 파일 수정
- api container profile prod 옵션 추가
=> [ECR-72] BE/fix : api container profile prod 설정

api/Dockerfile, api/build.gradle, api/src/main/resources/application-prod.properties, docker-compose.yml
- ECR-73
- build.gradle test -> prod 수정
- Dockerfile에 명시적으로 추가
=> [ECR-73] BE/fix : 프로파일 설정 추가

api/src/main/java/org/example/educheck/domain/absenceattendance/controller/AbsenceAttendanceController.java, api/src/main/java/org/example/educheck/domain/absenceattendance/dto/request/CreateAbsenceAttendacneRequestDto.java, api/src/main/java/org/example/educheck/domain/absenceattendance/service/AbsenceAttendanceService.java, api/src/main/java/org/example/educheck/global/common/config/AwsS3Config.java, api/src/main/java/org/example/educheck/global/common/s3/S3Service.java, api/src/main/resources/application.properties, client/src/api/absenceAttendancesApi.js, client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.jsx
- ECR-75
- 수강생 유고 결석 신청시 첨부파일 업로드 로직 개선
- 기존 : 서버를 통한 S3 업로드
변경 :  PresignedURL을 이용해서 클라이언트 -> S3 업로드로 리팩토링
=> [ECR-75] BE/refactor: 파일 업로드 시스템 개선

api/src/main/resources/application.properties
- ECR-77
- 테스트를 위해 첨부파일 업로드 사이즈 수정
=> [ECR-77] chore: 테스트를 위해 업로드 사이즈 조정

client/src/api/absenceAttendancesApi.js, client/src/components/buttons/mainButton/MainButton.jsx, client/src/components/buttons/mainButton/MainButton.module.css, client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.jsx
- ECR-76
- 파일 선택 즉시 S3 업로드로 리팩터링
- 업로드 중 제출 버튼 상태 관리 개선 (업로드중 및 비활성화 표기)
=> [ECR-76] refactor: 파일 업로드 로직 개선
